server:
  port: 3001
  address: 0.0.0.0

spring:
  application:
    name: api-wrapper
  profiles:
    active: production

app:
  environment: production
  server:
    port: 3001
    ip:
      development: localhost
      production: 192.168.120.4

logging:
  level:
    com.apitester.wrapper: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 